// <auto-generated />
using Data.Services.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace OnlineBookStore.Migrations
{
    [DbContext(typeof(OnlineBookStoreContext))]
    partial class OnlineBookStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.Models.AdministratorDTO", b =>
                {
                    b.Property<int>("AdministratorID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("AdministratorName")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR(32)");

                    b.Property<int>("PhoneNumber");

                    b.HasKey("AdministratorID");

                    b.ToTable("Administrator");
                });

            modelBuilder.Entity("Models.Models.BookDTO", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("BookName")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18,5)");

                    b.HasKey("BookID");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Models.Models.BookOrderDTO", b =>
                {
                    b.Property<int>("BookOrderID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookID");

                    b.Property<int>("CustmoerID");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18,5)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("DECIMAL(18,5)");

                    b.HasKey("BookOrderID");

                    b.ToTable("BookOrders");
                });

            modelBuilder.Entity("Models.Models.CustmoerDTO", b =>
                {
                    b.Property<int>("CustmoerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<int>("PhoneNumber");

                    b.HasKey("CustmoerID");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Models.Models.ShoppingCartDTO", b =>
                {
                    b.Property<int>("ShoppingCartID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BookOrderID");

                    b.Property<int>("CustmoerID");

                    b.Property<decimal>("Price")
                        .HasColumnType("DECIMAL(18,5)");

                    b.HasKey("ShoppingCartID");

                    b.ToTable("ShopingCart");
                });

            modelBuilder.Entity("Models.Models.UserDTO", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Username")
                        .HasColumnType("NVARCHAR(100)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
